/** Auto-generated by scripts/fetch-monsters.js — do not edit */
export const CREATURE_TYPES: string[] = [
  "aberration",
  "beast",
  "celestial",
  "construct",
  "dragon",
  "elemental",
  "fey",
  "fiend",
  "giant",
  "humanoid",
  "monstrosity",
  "ooze",
  "plant",
  "swarm of Tiny beasts",
  "undead",
];
